# Подготовка территорий

Используем класс `LandDataPreparator`, чтобы собрать единый набор данных и сохранить результат.

### Входные данные

**scenario_blocks_path = "../data/prostor/scenario_blocks.pickle"** — GeoDataFrame сценарных участков. Обязательные атрибуты: геометрия `geometry` (проекция в метрах), доли типов использования (`residential`, `business`, `recreation`, `industrial`, `transport`, `special`, `agriculture`), агрегированные показатели `land_use`, `share`, `footprint_area`, `build_floor_area`, `living_area`, `non_living_area`.

**context_blocks_path = "../data/prostor/context_blocks.pickle"** — GeoDataFrame контекстных участков с идентичной структурой и той же CRS; используется для объединения с сценарными блоками.

**accessibility_matrix_path = "../data/prostor/acc_mx.pickle"** — DataFrame с матрицей доступности, индекс которой синхронизирован с блоками, и обязательным набором показателей доступности (например `area_accessibility` и связанные метрики), которые функция `area_accessibility` переносит в итоговый GeoDataFrame.

In [1]:
import pandas as pd

scenario_blocks = pd.read_pickle('../data/scenario_198_blocks.pickle')
context_blocks = pd.read_pickle('../data/context_blocks.pickle')
accessibility_matrix = pd.read_pickle('../data/acc_mx_198.pickle')

In [2]:
scenario_blocks.head()

,geometry,residential,business,recreation,industrial,transport,special,agriculture,land_use,share
0,"POLYGON ((391069.678 6644283.933, 391050.241 6...",0.618414,0.044475,0.160341,0.0,0.0,0.001839,0.0,LandUse.RESIDENTIAL,0.618414
1,"POLYGON ((391050.241 6644214.883, 391069.678 6...",1.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,LandUse.RESIDENTIAL,1.000000
2,"POLYGON ((390977.168 6643926.423, 390992.271 6...",0.860749,0.000000,0.139251,0.0,0.0,0.000000,0.0,LandUse.RESIDENTIAL,0.860749
3,"POLYGON ((390992.271 6644001.941, 391006.969 6...",1.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,LandUse.RESIDENTIAL,1.000000
4,"POLYGON ((390959.455 6643851.451, 390977.168 6...",0.000000,0.737552,0.262448,0.0,0.0,0.000000,0.0,LandUse.BUSINESS,0.737552

In [3]:
context_blocks.head()

,geometry,residential,business,recreation,industrial,transport,special,agriculture,land_use,share,...,capacity_supermarket,count_supermarket,capacity_swimming_pool,count_swimming_pool,capacity_train_station,count_train_station,capacity_university,count_university,capacity_veterinary,count_veterinary
0,"POLYGON ((391549.648 6642620.924, 391440.516 6...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,NaN,...,5000,1,1000,1,0,0,0,0,0,0
1,"POLYGON ((390728.805 6642824.074, 390766.253 6...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,NaN,...,0,0,0,0,0,0,0,0,0,0
2,"POLYGON ((384619.942 6643780.507, 384592.897 6...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,NaN,...,0,0,0,0,0,0,0,0,0,0
3,"POLYGON ((383701.245 6643709.235, 384459.417 6...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,NaN,...,0,0,0,0,0,0,0,0,0,0
4,"POLYGON ((394792.785 6641449.688, 394618.737 6...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,NaN,...,0,0,0,0,0,0,0,0,0,0

In [4]:
from urbanomy.methods.land_value_modeling.land_data_preparation import LandDataPreparator

preparator = LandDataPreparator(
    scenario_blocks_source=scenario_blocks,
    context_blocks_source=context_blocks,
    accessibility_matrix_source=accessibility_matrix,
)

In [5]:
prepared_blocks = preparator.prepare()
prepared_blocks.head()

2025-10-28 16:57:20.052 | WARNING  | blocksnet.analysis.morphotypes.schemas:_before_validate:17 - Column l not found in columns. Calculating from fsi and gsi

,residential,business,recreation,industrial,transport,special,agriculture,land_use,share,footprint_area,...,site_area,fsi,gsi,mxi,l,morphotype,area_accessibility,is_scn,geometry,id
0,0.618414,0.044475,0.160341,0.0,0.0,0.001839,0.0,LandUse.RESIDENTIAL,0.618414,43743.312824,...,820351.893034,0.172159,0.053323,0.542771,3.228635,low-rise model,132.872848,True,"POLYGON ((391069.678 6644283.933, 391050.241 6...",0
1,1.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,LandUse.RESIDENTIAL,1.000000,11.720391,...,143.498624,0.241875,0.081676,0.578323,2.961395,low-rise model,135.391939,True,"POLYGON ((391050.241 6644214.883, 391069.678 6...",1
2,0.860749,0.000000,0.139251,0.0,0.0,0.000000,0.0,LandUse.RESIDENTIAL,0.860749,123.737389,...,708.434887,1.018722,0.174663,0.618815,5.832501,mid-rise,134.515316,True,"POLYGON ((390977.168 6643926.423, 390992.271 6...",2
3,1.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,LandUse.RESIDENTIAL,1.000000,62.624948,...,725.112337,0.277790,0.086366,0.629448,3.216435,low-rise model,134.633922,True,"POLYGON ((390992.271 6644001.941, 391006.969 6...",3
4,0.000000,0.737552,0.262448,0.0,0.0,0.000000,0.0,LandUse.BUSINESS,0.737552,79.773425,...,597.553304,0.309390,0.133500,0.000000,2.317526,low-rise non-residential,134.275676,True,"POLYGON ((390959.455 6643851.451, 390977.168 6...",4

In [6]:
prepared_blocks.to_pickle("../data/prepared_blocks_198.pickle")