In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
df = gpd.read_file('./data/blocks_investment.geojson')
df.head()

,land_use,land_area,built_area,land_cost,construction_cost,investment_need,NPV,IRR,ROI,PP_years,EI,spatial_potential,INV,geometry
0,LandUse.AGRICULTURE,202399.73,12550.41,3.132176e+08,3.137603e+08,6.269778e+08,-3.214205e+08,0.06,2.05,NaN,0.00,3.0,20.71,"POLYGON ((388511.373 6644951.946, 388558.037 6..."
1,LandUse.BUSINESS,201529.49,40777.54,3.488025e+08,2.242764e+09,2.591567e+09,2.027843e+09,0.33,12.29,6.69,100.00,2.0,58.57,"POLYGON ((388558.037 6645102.374, 388511.373 6..."
2,LandUse.TRANSPORT,164663.86,24985.65,2.232646e+08,4.497417e+08,6.730063e+08,5.106398e+06,0.18,5.93,17.49,1.90,4.0,42.54,"POLYGON ((387957.434 6643444.937, 388007.492 6..."
3,LandUse.RESIDENTIAL,161571.83,72568.69,7.195687e+08,3.265591e+09,3.985160e+09,5.519951e+08,0.24,3.11,5.51,72.68,4.0,84.00,"POLYGON ((388007.492 6643608.409, 387957.434 6..."
4,LandUse.RESIDENTIAL,49.93,2.17,4.938179e+04,9.764950e+04,1.470313e+05,-1.135879e+04,0.15,2.06,NaN,0.00,4.0,41.43,"POLYGON ((388000.75 6643199.606, 388001.306 66..."

In [3]:
import numpy as np

land_cost = pd.to_numeric(df['land_cost'], errors='coerce')
rng = np.random.default_rng(42)
df['land_cost_before'] = (land_cost * (0.93 - 0.05 * rng.random(len(df)))).round(2)
df.head()

,land_use,land_area,built_area,land_cost,construction_cost,investment_need,NPV,IRR,ROI,PP_years,EI,spatial_potential,INV,geometry,land_cost_before
0,LandUse.AGRICULTURE,202399.73,12550.41,3.132176e+08,3.137603e+08,6.269778e+08,-3.214205e+08,0.06,2.05,NaN,0.00,3.0,20.71,"POLYGON ((388511.373 6644951.946, 388558.037 6...",2.791715e+08
1,LandUse.BUSINESS,201529.49,40777.54,3.488025e+08,2.242764e+09,2.591567e+09,2.027843e+09,0.33,12.29,6.69,100.00,2.0,58.57,"POLYGON ((388558.037 6645102.374, 388511.373 6...",3.167323e+08
2,LandUse.TRANSPORT,164663.86,24985.65,2.232646e+08,4.497417e+08,6.730063e+08,5.106398e+06,0.18,5.93,17.49,1.90,4.0,42.54,"POLYGON ((387957.434 6643444.937, 388007.492 6...",1.980513e+08
3,LandUse.RESIDENTIAL,161571.83,72568.69,7.195687e+08,3.265591e+09,3.985160e+09,5.519951e+08,0.24,3.11,5.51,72.68,4.0,84.00,"POLYGON ((388007.492 6643608.409, 387957.434 6...",6.441087e+08
4,LandUse.RESIDENTIAL,49.93,2.17,4.938179e+04,9.764950e+04,1.470313e+05,-1.135879e+04,0.15,2.06,NaN,0.00,4.0,41.43,"POLYGON ((388000.75 6643199.606, 388001.306 66...",4.569253e+04

In [4]:
from urbanomy.methods.socio_economic_indicators.sei_calculate import SEREstimator

est = SEREstimator({
    'population': 500_000,
    'employment_base': 230_000,
})
result = est.compute(df, pretty=True)
result

,indicator,delta_build_year,delta_ops_year
0,Объём инвестиций в основной капитал на душу на...,128 634,
1,Валовый региональный продукт на душу населения,20 517,12 789
2,Доходы бюджета территории,8 543 412 354,4 294 420 827
3,Средний уровень заработной платы,,767
4,Износ основного фонда (тыс. руб.),,2 091 096