In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
df = gpd.read_file('./data/test/blocks_investment.geojson')
df

,land_use,land_area,built_area,land_cost,construction_cost,investment_need,NPV,IRR,ROI,PP_years,EI,spatial_potential,INV,geometry
0,AGRICULTURE,202399.73,12550.42,1.826177e+08,3.137604e+08,4.963782e+08,-2.654166e+08,0.00,1.18,NaN,0.00,3.0,21.36,"POLYGON ((388511.373 6644951.946, 388558.037 6..."
1,BUSINESS,201529.49,40777.55,2.063089e+08,2.242765e+09,2.449074e+09,1.654111e+08,0.13,4.50,13.40,37.52,2.0,21.49,"POLYGON ((388558.037 6645102.374, 388511.373 6..."
2,TRANSPORT,164663.86,24985.66,1.508134e+08,4.497418e+08,6.005553e+08,-1.275964e+08,0.08,2.92,NaN,0.00,4.0,42.73,"POLYGON ((387957.434 6643444.937, 388007.492 6..."
3,RESIDENTIAL,161571.83,72568.71,4.262998e+08,3.265592e+09,3.691892e+09,7.028120e+08,0.19,2.76,5.42,69.48,4.0,82.52,"POLYGON ((388007.492 6643608.409, 387957.434 6..."
4,RESIDENTIAL,49.93,2.17,3.985893e+04,9.764970e+04,1.375086e+05,-6.095550e+03,0.10,1.73,NaN,0.00,4.0,42.73,"POLYGON ((388000.75 6643199.606, 388001.306 66..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,BUSINESS,606.98,203.64,1.173200e+06,1.120007e+07,1.237327e+07,1.554828e+06,0.14,4.80,12.35,6.91,2.0,3.96,"POLYGON ((390950.379 6643779.96, 390941.389 66..."
63,AGRICULTURE,2.67,NaN,1.075884e+04,NaN,1.075884e+04,-2.424442e+04,0.06,2.54,NaN,0.00,3.0,21.36,"POLYGON ((391069.678 6644283.933, 391072.529 6..."
64,TRANSPORT,4307.66,688.58,4.339395e+06,1.239436e+07,1.673375e+07,-3.405068e+06,0.08,2.95,NaN,0.00,4.0,42.73,"POLYGON ((388222.552 6643218.262, 388215.418 6..."
65,BUSINESS,61.63,13.49,1.784116e+04,7.418000e+05,7.596412e+05,1.628409e+05,0.16,5.89,11.09,11.11,2.0,6.37,"POLYGON ((388314.421 6645193.77, 388311.871 66..."
66,SPECIAL,175.85,60.89,4.501139e+04,2.131233e+06,2.176245e+06,1.929766e+05,0.14,5.98,15.02,4.27,4.0,45.18,"POLYGON ((390404.263 6642900.867, 390408.695 6..."

In [3]:
import numpy as np

land_cost = pd.to_numeric(df['land_cost'], errors='coerce')
rng = np.random.default_rng(42)
df['land_cost_before'] = (land_cost * (0.93 - 0.05 * rng.random(len(df)))).round(2)
df

,land_use,land_area,built_area,land_cost,construction_cost,investment_need,NPV,IRR,ROI,PP_years,EI,spatial_potential,INV,geometry,land_cost_before
0,AGRICULTURE,202399.73,12550.42,1.826177e+08,3.137604e+08,4.963782e+08,-2.654166e+08,0.00,1.18,NaN,0.00,3.0,21.36,"POLYGON ((388511.373 6644951.946, 388558.037 6...",1.627676e+08
1,BUSINESS,201529.49,40777.55,2.063089e+08,2.242765e+09,2.449074e+09,1.654111e+08,0.13,4.50,13.40,37.52,2.0,21.49,"POLYGON ((388558.037 6645102.374, 388511.373 6...",1.873401e+08
2,TRANSPORT,164663.86,24985.66,1.508134e+08,4.497418e+08,6.005553e+08,-1.275964e+08,0.08,2.92,NaN,0.00,4.0,42.73,"POLYGON ((387957.434 6643444.937, 388007.492 6...",1.337821e+08
3,RESIDENTIAL,161571.83,72568.71,4.262998e+08,3.265592e+09,3.691892e+09,7.028120e+08,0.19,2.76,5.42,69.48,4.0,82.52,"POLYGON ((388007.492 6643608.409, 387957.434 6...",3.815945e+08
4,RESIDENTIAL,49.93,2.17,3.985893e+04,9.764970e+04,1.375086e+05,-6.095550e+03,0.10,1.73,NaN,0.00,4.0,42.73,"POLYGON ((388000.75 6643199.606, 388001.306 66...",3.688111e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,BUSINESS,606.98,203.64,1.173200e+06,1.120007e+07,1.237327e+07,1.554828e+06,0.14,4.80,12.35,6.91,2.0,3.96,"POLYGON ((390950.379 6643779.96, 390941.389 66...",1.057919e+06
63,AGRICULTURE,2.67,NaN,1.075884e+04,NaN,1.075884e+04,-2.424442e+04,0.06,2.54,NaN,0.00,3.0,21.36,"POLYGON ((391069.678 6644283.933, 391072.529 6...",9.594200e+03
64,TRANSPORT,4307.66,688.58,4.339395e+06,1.239436e+07,1.673375e+07,-3.405068e+06,0.08,2.95,NaN,0.00,4.0,42.73,"POLYGON ((388222.552 6643218.262, 388215.418 6...",3.897923e+06
65,BUSINESS,61.63,13.49,1.784116e+04,7.418000e+05,7.596412e+05,1.628409e+05,0.16,5.89,11.09,11.11,2.0,6.37,"POLYGON ((388314.421 6645193.77, 388311.871 66...",1.609845e+04
66,SPECIAL,175.85,60.89,4.501139e+04,2.131233e+06,2.176245e+06,1.929766e+05,0.14,5.98,15.02,4.27,4.0,45.18,"POLYGON ((390404.263 6642900.867, 390408.695 6...",4.060206e+04

In [4]:
from urbanomy.methods.ser.ser_calculate import SEREstimator

est = SEREstimator({
    'population': 500_000,
    'employment_base': 230_000,
})
result = est.compute(df, pretty=True)
result

,indicator,delta_build_year,delta_ops_year
0,Объём инвестиций в основной капитал на душу на...,120 191,
1,Валовый региональный продукт на душу населения,19 172,12 789
2,Доходы бюджета территории,7 982 676 014,4 209 011 873
3,Средний уровень заработной платы,,807
4,Износ основного фонда (тыс. руб.),,1 947 548